#!/bin/bash
# I want UD1035 hyp7GEM deltaK_1.nd2 ... into UD1035_hyp7GEM_deltaK_1.nd2 ...
for file in UD1035\ hyp7GEM\ deltaK_*.nd2; do
  new_name="${file// /_}"
  mv -- "$file" "$new_name"
  echo "Renamed $file to $new_name"
done
